#
# Copyright (c) 2015-2016, Stuart Wheater, Newcastle upon Tyne, England. All rights reserved.
#

clean:
	$(MAKE) -C mkx2x clean
	$(MAKE) -C sam3x clean
	$(MAKE) -C atmega clean
	$(MAKE) -C attiny clean
	$(RM) $(RMFLAGS) *~ *.o
