#
# Copyright (c) 2015-2016, Stuart Wheater, Newcastle upon Tyne, England. All rights reserved.
#

all:

clean:
	$(MAKE) -C mkx2x clean
	$(MAKE) -C sam3x clean
	$(MAKE) -C atmega clean
	$(RM) -f *~ *.o
