#
# Copyright (c) 2015-2016, Stuart Wheater, Newcastle upon Tyne, England. All rights reserved.
#
export MAKE         = make
export RM           = rm


all:
	$(MAKE) -C dGenerator all

clean:
	$(MAKE) -C dGenerator clean
	$(RM) -f *~
